config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :artifacts
  resources :user_projects
  put 'user_projects', to: "user_projects#create"
  resources :items
  resources :projects
  resources :organizations
  root 'organizations#home'
  get 'search_organization', to: 'organizations#search'
  get 'dashboard', to: 'pages#home'

  devise_for :admins, controllers: {sessions: "sessions", invitations: "invitations"} 
  devise_for :members, controllers: {sessions: "sessions", invitations: "invitations"}
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

match 'plan/edit' => 'organizations#edit', via: :get, as: :edit_plan
match 'plan/update' => 'organizations#update', via: [:put, :patch], as: :update_plan
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  before_action :set_user_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :require_admin

  # GET /user_projects or /user_projects.json
  def index
    @user_projects = UserProject.all
  end

  # GET /user_projects/1 or /user_projects/1.json
  def show
  end

  # GET /user_projects/new
  def new
    @user_project = UserProject.new
  end

  # GET /user_projects/1/edit
  def edit
  end

  # POST /user_projects or /user_projects.json
  def create
    @user_project = UserProject.new(user_id: params[:user_id], project_id: params[:project_id])

    respond_to do |format|
      if @user_project.save
        format.html { redirect_to @user_project, notice: "User project was successfully created." }
        format.json { render :show, status: :created, location: @user_project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_projects/1 or /user_projects/1.json
  def update
    respond_to do |format|
      if @user_project.update(user_project_params)
        format.html { redirect_to @user_project, notice: "User project was successfully updated." }
        format.json { render :show, status: :ok, location: @user_project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_projects/1 or /user_projects/1.json
  def destroy
    @user_project.destroy
    respond_to do |format|
      format.html { redirect_to user_projects_url, notice: "User project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_project
      @user_project = UserProject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_project_params
      params.require(:user_project).permit(:project_id, :user_id)
    end

    def require_admin
      return if current_user.type == "Admin"
      flash[:alert] = 'Access denied'
      redirect_to dashboard_path
    end
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/views/user_projects/_form.html.erb
<%= form_with(model: user_project) do |form| %>
  <% if user_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_project.errors.count, "error") %> prohibited this user_project from being saved:</h2>

      <ul>
        <% user_project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_projects/edit.html.erb
<h1>Editing User Project</h1>

<%= render 'form', user_project: @user_project %>

<%= link_to 'Show', @user_project %> |
<%= link_to 'Back', user_projects_path %>

app/views/user_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Projects</h1>
<% if @user_projects.count <= 0 %>
  <p>No employee added to project</p>
  <% else %>
<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_projects.each do |user_project| %>
      <tr>
        <td><%= user_project.project.name%></td>
        <td><%= user_project.user.email %></td>
        <td><%= link_to 'Show', user_project %></td>
        <td><%= link_to 'Edit', edit_user_project_path(user_project) %></td>
        <td><%= link_to 'Destroy', user_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New User Project', new_user_project_path %> |
<%= link_to 'Back', dashboard_path %>

app/views/user_projects/new.html.erb
<h1>New User Project</h1>

<%= render 'form', user_project: @user_project %>

<%= link_to 'Back', user_projects_path %>

app/views/user_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @user_project.project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_project.user.email%>
</p>

<%= link_to 'Edit', edit_user_project_path(@user_project) %> |
<%= link_to 'Back', project_path(@user_project.project_id) %>