config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :artifacts
  resources :user_projects
  put 'user_projects', to: "user_projects#create"
  resources :items
  resources :projects
  resources :organizations
  root 'organizations#home'
  get 'search_organization', to: 'organizations#search'
  get 'dashboard', to: 'pages#home'

  devise_for :admins, controllers: {sessions: "sessions", invitations: "invitations"} 
  devise_for :members, controllers: {sessions: "sessions", invitations: "invitations"}
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

match 'plan/edit' => 'organizations#edit', via: :get, as: :edit_plan
match 'plan/update' => 'organizations#update', via: [:put, :patch], as: :update_plan
end

app/models/organization.rb
class Organization < ApplicationRecord
    # acts_as_universal_and_determines_tenant
    has_many :members, dependent: :destroy
    has_many :projects, dependent: :destroy
    has_one :payment
    accepts_nested_attributes_for :payment
    validates :name, presence: true, uniqueness: true

    def can_create_projects?
      (plan == 'free' && projects.count < 1) || (plan == 'premium')
    end

    def org_is_in_db?(subdomain)
      organization = check_db(subdomain).exists?
    end
    
    def self.check_db(subdomain)
      where(subdomain: subdomain).first
    end

    def self.create_new_tenant(organization_params, user_params)
      tenant = Tenant.new(organization_params_params)
      organization.save    # create the org
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  protect_from_forgery prepend: true, with: :null_session
  before_action :set_organization, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[create new home]
  # before_action :require_admin, except: %i[create new]



  # GET /organizations or /organizations.json
  def home

  end
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1 or /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations or /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to  new_admin_registration_url(subdomain: @organization.subdomain), notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    respond_to do |format|
      Organization.transaction do
        if @organization.update(organization_params)
          if @organization.plan == "premium" && @organization.payment.blank?
            @payment = Payment.new({email: organization_params["email"],
                                    token: params[:payment]["token"],
                                    organization: @organization})
            begin
              @payment.process_payment
              @payment.save
            rescue Exception => e
              flash[:error] = e.message
              @payment.destroy
              @organization.plan = "free"
              @organization.save
              
              redirect_to edit_organization_path(@organization) and return
            end
          end
          format.html { redirect_to @organization, notice: "Organization was successfully updated." }
          format.json { render :show, status: :ok, location: @organization }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @organization.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @organization = Organization.check_db(params[:organization])
    if @organization
      @organization
    else
      flash[:alert] = "Organization doesn't exists."
    end
    render 'organizations/home'
  end

  def change
    @organization = Organization.find(params[:id])
    Organization.set_current_organization @organization.id
    session[:organization_id] = Organization.current_organization.id
    redirect_to home_index_path, notice: "Switched to organization: #{organization.name}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name, :subdomain, :domain, :plan)
    end

    def require_admin
      return if current_user.type == "Admin"
      flash[:alert] = 'Access denied'
      redirect_to dashboard_path
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<script language="Javascript">
  Stripe.setPublishableKey("<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>");
</script>

<%= form_with(model: organization, html: { role: "form", class: 'cc_form'}) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% form.label :name %>
    <%= form.text_field :name, class: "form-control mt-3 mb-3", style: 'width: 60%', placeholder: "Organization name" %>
  </div>

  <div class="field">
    <% form.label :subdomain %>
    <%= form.text_field :subdomain, class: "form-control mt-3 mb-3", style: 'width: 60%', placeholder: "Subdomain" %>
  </div>

  <div class="field">
    <% form.label :domain %>
    <%= form.text_field :domain,class: "form-control mt-3 mb-3", style: 'width: 60%', placeholder: "Domain" %>
  </div>

 <%= fields_for(:organization) do |w| %>
    <div class="form-group col-md-6 no-right-padding">
        <%= w.label :plan, class: "h6" %>
        <%= w.select :plan, options_for_select(Plan.options, params[:plan]), {}, required: true, class: "form-control mb-3" %>
      </div>
    <%end%>

<h6>Payment method:</h6>

<%= form_for @organization, url: update_plan_path, html: {class: "#{class_name_for_organization_form(@organization)}"} do |f| %>
    <% if @organization.payment.blank?%>
        <%= fields_for(:payment) do |p| %>
        <div class="row col-md-12">
            <div class="form-group col-md-4 no-left-padding">    
                <% p.label :card_number, "Card Number", data: {stripe: 'label'} %>
                <%= p.text_field :card_number, class: "form-control mt-3 mb-3", placeholder: "Card Number", required: true, data: {stripe: 'number'} %>
            </div>
            <div class="form-group col-md-12">
                <% p.label :card_cvv, "Card CVV", data: {stripe: 'label'} %>
                <%= p.text_field :card_cvv,  class: "form-control mb-3", style: "width: 31%", placeholder: "Card CVV", required: true, data: {stripe: 'cvv'} %>
            </div>
            <div class="form-group col-md-6">
                <div class="col-md-12">
                        <%= p.label :card_expires, "Card Expiration Date", class: "h6", data: {stripe: 'label'} %>
                </div>
                <div class="col-md-3">
                        <%= p.select :card_expires_month,
                                    options_for_select(Payment.month_options),
                                    { include_blank: 'Month'},
                                    'data-stripe' => "exp-month",
                                    class: "form-control mt-3 mb-3", required: true %>
                </div>
                <div class="col-md-3">
                        <%= p.select :card_expires_year,
                                    options_for_select(Payment.year_options.push),
                                    { include_blank: 'Year'},
                                    class: "form-control mb-3",
                                    data: {stripe: "exp-year"}, required: true 
                        %>
                </div>
            </div>    
        </div>
    <div class="actions">
      <%= form.submit "Create Organization", class: "btn btn-primary" %>
    </div>      
        <% end %>
    <% end %>    
<% end %>

<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/home.html.erb
<div class="d-flex flex-column align-items-center">
<h1>Project Management App</h1>

<% if user_signed_in? %>
  <h2>Welcome </h2>
<%= link_to 'Add Project',  new_project_path %>

<% else %>
  <h3>Welcome! Enter Your Organization Subdomain</h3>
  <%= form_with url: search_organization_path, method: :get do |form| %>
    <div class="input-group w-100 ">
    <%= form.text_field :organization, class:"form-control fs-5 border-info shadow-none", placeholder:"Enter Subdomain" %>
     <button class="input-group-text btn-lg bg-info text-dark border-info" id="basic-addon1" type="submit" value="Search" class="btn btn-success fw-bold"> 
        <i class="bi bi-search bigger fs-4 " ></i>
      </button>
    </div>
  <% end %>
  
  <% if @organization %>
  <div class="my-3 bg-secondary text-light rounded-3 px-4 py-2 text-uppercase">
    <h4 class="text-center" ><%= @organization.name %> </h4>
    <div class='control-group' >
    <%= link_to 'Sign In as admin',  new_admin_session_url(subdomain: @organization.subdomain), class:"text-info text-decoration-none" %> | 
    <%= link_to 'Sign In as member',  new_member_session_url(subdomain: @organization.subdomain), class:"text-info text-decoration-none" %>
    </div>
  <% else %>
     <%= link_to 'Create Organization', new_organization_path, class:"text-decoration-none btn btn-info mt-2 fw-bold" %> 
<% end %>
<% end %>
</div>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subdomain</th>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.subdomain %></td>
        <td><%= organization.domain %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= form_with(model: @organization, html: { role: "form", class: 'cc_form'}) do |form| %>
  <% if @organization.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

            <ul>
                <% organization.errors.each do |error| %>
                <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div class="field">
    <% form.label :name %>
    <%= form.text_field :name, class: "form-control mt-3 mb-3", style: 'width: 60%', placeholder: "Organization name" %>
  </div>

  <div class="field">
    <% form.label :subdomain %>
    <%= form.text_field :subdomain, class: "form-control mt-3 mb-3", style: 'width: 60%', placeholder: "Subdomain" %>
  </div>

  <div class="field">
    <% form.label :domain %>
    <%= form.text_field :domain,class: "form-control mt-3 mb-3", style: 'width: 60%', placeholder: "Domain" %>
  </div>
  

<div class="actions">
    <%= form.submit "Create Organization", class: "btn btn-primary" %>
</div>      

<%= link_to 'Back', root_path %>

<% end %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @organization.subdomain %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @organization.domain %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>