config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :artifacts
  resources :user_projects
  put 'user_projects', to: "user_projects#create"
  resources :items
  resources :projects
  resources :organizations
  root 'organizations#home'
  get 'search_organization', to: 'organizations#search'
  get 'dashboard', to: 'pages#home'

  devise_for :admins, controllers: {sessions: "sessions", invitations: "invitations"} 
  devise_for :members, controllers: {sessions: "sessions", invitations: "invitations"}
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

match 'plan/edit' => 'organizations#edit', via: :get, as: :edit_plan
match 'plan/update' => 'organizations#update', via: [:put, :patch], as: :update_plan
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  belongs_to :project
  has_many :tasks
  validates :name, presence: true, uniqueness: true
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: %i[ show edit update destroy ]

  # GET /artifacts or /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1 or /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
    @artifact.project_id = params[:project_id]
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts or /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to project_path(artifact_params[:project_id]), notice: "Artifact was successfully created." }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1 or /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to @artifact, notice: "Artifact was successfully updated." }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1 or /artifacts/1.json
  def destroy
    @artifact.destroy
    respond_to do |format|
      format.html { redirect_to artifacts_url, notice: "Artifact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artifact_params
      params.require(:artifact).permit(:name, :project_id)
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_form.html.erb
<%= form_with(model: artifact) do |form| %>
  <% if artifact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
        <% artifact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.hidden_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artifacts/_table.html.erb
<% if @artifacts.exists? %>
  <% @artifacts.map do |artifact| %>
    <table class="table table-hover">
    <thead>
        <tr>
        <th scope="col"><%= artifact.name %></th>
        <th scope="col" class="text-center">Status</th>
        <th scope="col" class="text-center">Priority</th>
        <th scope="col" class="text-center">Timeline</th>
        <th scope="col" class="text-center">Related Files</th>
        <th scope="col" class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
      <% if @tasks.exists? %>
        <% @tasks.map do |task| %>
            <tr>
          <% if task.artifact_id == artifact.id %>
            <th scope="row"><%= task.name %></th>
            <% if task.status == 'done' %>
            <td class="text-center"><%= '<i class="bi bi-clipboard-check fs-4 text-success"></i>'.html_safe %></td>
            <% elsif task.status == 'on-going' %>
            <td class="text-center"><%= '<i class="bi bi-clipboard fs-4 text-primary"></i>'.html_safe %></td>
            <% else %>
               <td class="text-center"><%= '<i class="bi bi-clipboard-x fs-4 text-danger"></i>'.html_safe %></td>
             <% end %>
            <% if task.priority == 'high' %>
            <td class="text-center"><%= '<i class="bi bi-circle-fill text-danger"></i>'.html_safe %></td>
            <% elsif task.priority == 'medium' %>
            <td class="text-center"><%= '<i class="bi bi-circle-fill text-warning"></i>'.html_safe %></td>
            <% else task.priority == 'medium' %>
            <td class="text-center text-info"><%= '<i class="bi bi-circle-fill text-info"></i>'.html_safe %></td>
           <% end %>
            <td class="text-center"><%= task.starting_date %> to <%= task.completion_date %></td>
            <td class="text-center"><%= link_to 'See Files', items_path(project_id: @project.id, task_id: task.id) %> | <%= link_to 'Upload File', new_item_path(project_id: @project.id, task_id: task.id) %></td>
            <td class="text-center"><%= link_to 'Update Task', edit_task_path(id: task.id, project_id: @project.id, artifact_id: artifact.id) %> | <%= link_to 'Delete task', task_path(id: task.id, project_id: @project.id), method: :delete %></td>
          <% end %>
            </tr>
        <% end %>
      <% else %>
        <tr>
         <td> <p> Start adding Tasks </p> </td>
        </tr>
      <% end %>
    </tbody>
    </table>
    <%= link_to 'Add task', new_task_path(project_id: @project.id, artifact_id: artifact.id) %>
  <% end %>
<% else %>
  <h1>Start Creating New Artifacts</h1>
  
<% end %>

app/views/artifacts/edit.html.erb
<h1>Editing Artifact</h1>

<%= render 'form', artifact: @artifact %>

<%= link_to 'Show', @artifact %> |
<%= link_to 'Back', artifacts_path %>

app/views/artifacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artifacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><%= artifact.name %></td>
        <td><%= artifact.project_id %></td>
        <td><%= link_to 'Show', artifact %></td>
        <td><%= link_to 'Edit', edit_artifact_path(artifact) %></td>
        <td><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artifact', new_artifact_path %>

app/views/artifacts/new.html.erb
<h1>New Artifact</h1>

<%= render 'form', artifact: @artifact %>

<%= link_to 'Back', artifacts_path %>

app/views/artifacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artifact.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @artifact.project_id %>
</p>

<%= link_to 'Edit', edit_artifact_path(@artifact) %> |
<%= link_to 'Back', artifacts_path %>