config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :artifacts
  resources :user_projects
  put 'user_projects', to: "user_projects#create"
  resources :items
  resources :projects
  resources :organizations
  root 'organizations#home'
  get 'search_organization', to: 'organizations#search'
  get 'dashboard', to: 'pages#home'

  devise_for :admins, controllers: {sessions: "sessions", invitations: "invitations"} 
  devise_for :members, controllers: {sessions: "sessions", invitations: "invitations"}
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

match 'plan/edit' => 'organizations#edit', via: :get, as: :edit_plan
match 'plan/update' => 'organizations#update', via: [:put, :patch], as: :update_plan
end

app/models/admin.rb
class Admin < User
  devise :database_authenticatable, :validatable
  include DeviseInvitable::Inviter
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  belongs_to :project
  has_many :tasks
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  before_save :upload_to_s3
  attr_accessor :upload
  belongs_to :project
  belongs_to :task


  def upload_to_s3
    s3 = Aws::S3::Resource.new(region:'us-east-2')
    org =  User.find(ActsAsTenant.current_tenant.id).organization.name
    obj = s3.bucket(ENV['S3_BUCKET']).object("#{org}/#{upload.original_filename}")
    obj.upload_file(upload.path, acl:'public-read', content_type:"")
    self.key = obj.public_url
  end

end

app/models/member.rb
class Member < User
end

app/models/organization.rb
class Organization < ApplicationRecord
    # acts_as_universal_and_determines_tenant
    has_many :members, dependent: :destroy
    has_many :projects, dependent: :destroy
    has_one :payment
    accepts_nested_attributes_for :payment
    validates :name, presence: true, uniqueness: true

    def can_create_projects?
      (plan == 'free' && projects.count < 1) || (plan == 'premium')
    end

    def org_is_in_db?(subdomain)
      organization = check_db(subdomain).exists?
    end
    
    def self.check_db(subdomain)
      where(subdomain: subdomain).first
    end

    def self.create_new_tenant(organization_params, user_params)
      tenant = Tenant.new(organization_params_params)
      organization.save    # create the org
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
  acts_as_tenant :organization
  attr_accessor :card_number, :card_cvc, :card_expires_month, :card_expires_year

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1] } 
  end  
  
  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create email: email, card: token
      
    Stripe::Charge.create customer: customer.id, 
                          amount: 1000, 
                          description: 'Premium', 
                          currency: 'usd'

  end
end

app/models/plan.rb
class Plan 
    PLANS = [:free, :premium]

    def self.options
        PLANS.map { |plan| [plan.capitalize, plan]}
    end
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :organization
  has_many :items, dependent: :destroy
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :artifacts
  has_many :tasks
  has_many :items
  validate :free_plan_can_only_have_one_project
  validates :name, presence: true, uniqueness: true
  validates :completion_date, presence: true
  def free_plan_can_only_have_one_project
    if self.new_record? && (organization.projects.count > 0) && (organization.plan == 'free')
      errors.add(:base, "Free plans cannot have more than one project.")
    end
  end

  def self.by_user_plan_and_tenant(organization_id, user)
    organization = Organization.find(organization_id)
    if organization.plan == 'premium'
      if user.is_admin?
        organization.projects
      else
        user.projects.where(organization_id: organization.id)
      end
    else
      if user.type == "Admin"
        organization.projects.order(:id).limit(1)
      else
        user.projects.where(organization_id: organization.id).order(:id).limit(1)
      end
    end
  end
end

app/models/related_file.rb
class RelatedFile < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :artifact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  acts_as_tenant :organization
  accepts_nested_attributes_for :organization
  has_many :user_projects
  has_many :projects, through: :user_projects
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  def index
    @items = Item.where(project_id: params[:project_id], task_id: params[:task_id])
  end
  # GET /items/1 or /items/1.json
  def show
    @projects = Project.all
  end

  # GET /items/new
  def new
    @item = Item.new
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
  end


  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :project_id, :task_id, :upload)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def oraganization_name(organization_id)
        Organization.find(organization_id).name
    end
    
      def s3_link(organization_id, item_key)
        link_to item_key, "#{item_key}", class: "main-link", target: 'new'
      end

    ALERT_TYPE = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

    def bootstrap_flash(options = {})
        flash_messages = []
        flash.each do |type, message|
            next if message.blank

            type = type.to_sym
            type = :success if type == :notice
            type = :danger if type == :alert
            type = :danger if type == :error
            
            next unless ALERT_TYPES.include? (type)

            tag_class = options.extract!(:class)[:class]
            tag_options = {
                class: "alert fade in alert-#{type} #{tag_class}"
                }.merge(options)

            close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

            Array(message).each do |msg|
                text = content_tag(:div, close_button + msg, tag_options)
                flash_messages << text if msg
            end
        end
        flash_messages.join("\n").html_safe
    end

    def class_name_for_organization_form(organization)
        return "cc_form" if organization.payment.blank?
        ""
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/layouts/_message.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<div class='d-flex justify-content-center message'>
    <% flash.each do |name, msg| %>
        <div class="mt-2 mb-0 alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label=<%= name == "notice" ? "Success:" : "Danger:" %>><use xlink:href="<%= name == "notice" ? "#check-circle-fill" : "#exclamation-triangle-fill" %>"/></svg>
            <%= msg %>
             <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
        <% if user_signed_in? %>
                <iframe src="https://giphy.com/embed/YMwcy2pjfZc7bqON1x" style="pointer-events:none;" width="50" height="50" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
            <% else %>
                <iframe src="https://giphy.com/embed/YMwcy2pjfZc7bqON1x" style="pointer-events:none;" width="50" height="50" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNavDropdown">
            <% if user_signed_in? %>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <%= link_to 'Home', dashboard_path, class: "nav-link active" %>
                    </li>
                    <% if current_user.type == "Admin" %>
                        <li class="nav-item">
                        <%= link_to 'New Project', new_project_path, class: "nav-link active" %>
                        </li>
                    <% end %>
                    <% if current_user.type === "Admin" %>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Invite
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><%= link_to 'Invite Member', new_member_invitation_path, class: "dropdown-item" %></li>
                            <li><%= link_to 'Invite Admin', new_admin_invitation_path, class: "dropdown-item" %></li>
                        </ul>
                        </li>
                    <% end %>
                </ul>
                  <% else %>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <%= link_to 'Home', root_path, class: "nav-link active" %>
                    </li>
                      
                    <li class="nav-item">
                        <%= link_to 'Create Organization', new_organization_path, class:"nav-link text-white" %> 
                    </li>
                </ul>
            <% end %>
           

            
            <% if user_signed_in?  %>
                <ul class="navbar-nav ml-auto">
                <% if current_user.type === "Admin" %>
                    <li class="nav-item active">
                    <li class="nav-item active"><span class="nav-link">Admin</span></li>
                        <%= link_to 'Sign Out', destroy_admin_session_path, method: :get, class: "nav-link" %>
                    </li>
                 <% else %>
                    <li class="nav-item active">
                    <li class="nav-item active"><span class="nav-link">Member</span></li>
                        <%= link_to 'Sign Out', destroy_member_session_path, method: :get, class: "nav-link" %>
                    </li>
                <% end %>
              
            <% else %>
                <% if Organization.check_db(params[:organization]) %>
                <div class="dropdown ml-auto ">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Sign In
                    </button>
                    <ul class="dropdown-menu mx-auto" aria-labelledby="dropdownMenuButton1">
                        <li><%= link_to 'Admin Sign In',  new_admin_session_url(subdomain: @organization.subdomain), class: "dropdown-item" %></li>
                        <li><%= link_to 'Member Sign In',  new_member_session_url(subdomain: @organization.subdomain), class: "dropdown-item" %></li>
                    </ul>
                </div>
             
                <% end %>
                   </ul>
            <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "https://js.stripe.com/v2" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'credit_card_form', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
    <div style="height: 4.5rem;">
      <%= render "layouts/message" %>
    </div>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Project Management App</h1>
<% if user_signed_in? %>
  <h3>List of Org Projects</h3>
  <% if @projects.count == 0 %>
    <p>No Projects to Display </p>
  <% else %>
    <ul class="list-group">
    <% @projects.map do |project| %>
      <li class="list-group-item text-dark"><%= link_to project.name, project, class:"text-dark text-decoration-none" %></li>

    <% end %>
    </ul>
  <% end %>
  <h3>List of Org's Employee </h3>
  <% if @members.count == 0 %>
    <p>No Members to Display </p>
  <% else %>
    <ul class="list-group">
    <% @members.map do |member| %>
      <li class="list-group-item"><%= member.email %>
        
        </td></li>
    <% end %>
    </ul>
  <% end %>
<% else %>
  <h1> Welcome</h1>
<% end %>